### ISSUE TITLE
Create Ribose Metanorma document for this repo

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/concept-model#34]
Publish the concept model in a Metanorma document (Ribose flavor) that includes/links the two different schemas (and their versions in the future).

This way we can deploy on GitHub Pages.

_Originally posted by @ronaldtse in https://github.com/glossarist/concept-model/issues/33#issuecomment-1705441912_

**Comment by HassanAkbar** [comment]
@ronaldtse Currently, I'm creating a `ribose flavored adoc` file which will contain the link to the `concept` and `localizedConcept` models, the issue is that the HTML for the `concept` model is generated inside the workflow, so how can we link to that inside the `.adoc` file before the HTML is generated?

**Comment by ronaldtse** [comment]
For now, just include the YAML schema in a source code YAML block. 

We will deal with a HTML inclusion later.
